"""
optimizer.py  ─  3D Container Loading Optimizer
================================================
Shared algorithm module used by both the Jupyter Notebook and the Desktop App.

Algorithms implemented
──────────────────────
  1. Greedy Best-Fit Decreasing (BFD)
  2. Genetic Algorithm           (GA)
  3. Simulated Annealing         (SA)

All three algorithms use the same core decoder (pack_sequence) which implements
a Deepest-Bottom-Left-Fill strategy with candidate-point enumeration.
"""

from __future__ import annotations

import math
import random
import time
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

random.seed(42)


# ═══════════════════════════════════════════════════════════════════════════════
#  DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class Box:
    """A single rectangular box to be packed."""

    id: int
    length: float
    width: float
    height: float
    weight_kg: float
    fragile: bool = False

    @property
    def volume(self) -> float:
        return self.length * self.width * self.height

    def get_orientations(self) -> List[Tuple[float, float, float]]:
        """Return all physically valid orientations (L, W, H permutations)."""
        l, w, h = self.length, self.width, self.height
        if self.fragile:
            # Fragile: only rotate in the horizontal plane (height stays fixed)
            return [(l, w, h), (w, l, h)]
        return [
            (l, w, h), (l, h, w),
            (w, l, h), (w, h, l),
            (h, l, w), (h, w, l),
        ]

    def orientation_labels(self) -> List[str]:
        return [f"{o[0]}×{o[1]}×{o[2]} cm" for o in self.get_orientations()]

    def __repr__(self) -> str:
        return (f"Box(id={self.id}, {self.length}×{self.width}×{self.height}, "
                f"wt={self.weight_kg}kg, fragile={self.fragile})")


@dataclass
class Container:
    """The shipping container to pack boxes into."""

    name: str
    length: float
    width: float
    height: float

    @property
    def volume(self) -> float:
        return self.length * self.width * self.height

    def __str__(self) -> str:
        return f"{self.name} ({self.length}×{self.width}×{self.height} cm)"


# ═══════════════════════════════════════════════════════════════════════════════
#  PRESET CONTAINERS
# ═══════════════════════════════════════════════════════════════════════════════

PRESET_CONTAINERS: List[Container] = [
    Container("ISO 20ft Container",  589.0, 235.0, 239.0),
    Container("ISO 40ft Container", 1203.0, 235.0, 239.0),
    Container("Standard Truck",      600.0, 240.0, 250.0),
    Container("Delivery Van",        250.0, 160.0, 160.0),
    Container("Pallet Box",          120.0,  80.0, 100.0),
]


# ═══════════════════════════════════════════════════════════════════════════════
#  CORE PACKING ENGINE  (shared decoder for all three algorithms)
# ═══════════════════════════════════════════════════════════════════════════════

def check_overlap(p1: Tuple, d1: Tuple, p2: Tuple, d2: Tuple) -> bool:
    """Return True if two axis-aligned boxes overlap."""
    x1, y1, z1 = p1;  l1, w1, h1 = d1
    x2, y2, z2 = p2;  l2, w2, h2 = d2
    return not (x1 + l1 <= x2 or x2 + l2 <= x1 or
                y1 + w1 <= y2 or y2 + w2 <= y1 or
                z1 + h1 <= z2 or z2 + h2 <= z1)


def is_supported(x: float, y: float, z: float,
                 l: float, w: float,
                 placed: List[dict]) -> bool:
    """
    Gravity constraint: a box at height z=0 rests on the floor.
    Otherwise it must have at least partial overlap with a box below.
    """
    if z < 1e-6:
        return True
    for pb in placed:
        px, py, pz = pb["pos"];  pl, pw, ph = pb["dim"]
        if abs((pz + ph) - z) < 0.01:
            ox = min(x + l, px + pl) - max(x, px)
            oy = min(y + w, py + pw) - max(y, py)
            if ox > 0 and oy > 0:
                return True
    return False


def pack_sequence(
    sequence: List[Box],
    container: Container
) -> Tuple[List[dict], float]:
    """
    Core decoder — Deepest Bottom-Left Fill with candidate-point enumeration.

    For each box in *sequence* try every orientation and every candidate point.
    A candidate point is generated by extending the corner of each placed box.
    Heavy boxes score worse when placed high (stability heuristic).

    Parameters
    ----------
    sequence  : ordered list of Box objects (the 'chromosome')
    container : target Container

    Returns
    -------
    placed    : list of placement dicts
                { 'id', 'pos':(x,y,z), 'dim':(l,w,h),
                  'weight', 'fragile', 'original_box' }
    util_pct  : volume utilisation in [0, 100]
    """
    placed: List[dict] = []
    candidates: List[Tuple[float, float, float]] = [(0.0, 0.0, 0.0)]
    vol_packed = 0.0

    for box in sequence:
        best_pos = best_ori = None
        best_score = float("inf")

        for ori in box.get_orientations():
            bl, bw, bh = ori
            for cx, cy, cz in candidates:
                # Boundary check
                if (cx + bl > container.length or
                        cy + bw > container.width or
                        cz + bh > container.height):
                    continue
                # Gravity check
                if not is_supported(cx, cy, cz, bl, bw, placed):
                    continue
                # Overlap check
                if any(check_overlap((cx, cy, cz), (bl, bw, bh),
                                     pb["pos"], pb["dim"])
                       for pb in placed):
                    continue
                # Scoring: prefer lower & left-front; penalise heavy boxes placed high
                score = cx + cy + cz + cz * box.weight_kg
                if score < best_score:
                    best_score = score
                    best_pos = (cx, cy, cz)
                    best_ori = ori

        if best_pos:
            bx, by, bz = best_pos;  bl, bw, bh = best_ori
            placed.append({
                "id":           box.id,
                "pos":          best_pos,
                "dim":          best_ori,
                "weight":       box.weight_kg,
                "fragile":      box.fragile,
                "original_box": box,
            })
            vol_packed += bl * bw * bh
            # Add the three new candidate points from this box's far corners
            candidates.extend([
                (bx + bl, by,      bz),
                (bx,      by + bw, bz),
                (bx,      by,      bz + bh),
            ])

    util_pct = (vol_packed / container.volume) * 100.0 if container.volume > 0 else 0.0
    return placed, util_pct


def pack_sequence_with_forced(
    sequence: List[Box],
    container: Container,
    forced_orientations: Dict[int, Tuple[float, float, float]],
) -> Tuple[List[dict], float]:
    """Like pack_sequence but honour forced orientations for specific box IDs."""
    placed: List[dict] = []
    candidates = [(0.0, 0.0, 0.0)]
    vol_packed = 0.0

    for box in sequence:
        oris = ([forced_orientations[box.id]] if box.id in forced_orientations
                else box.get_orientations())
        best_pos = best_ori = None
        best_score = float("inf")

        for ori in oris:
            bl, bw, bh = ori
            for cx, cy, cz in candidates:
                if (cx + bl > container.length or
                        cy + bw > container.width or
                        cz + bh > container.height):
                    continue
                if not is_supported(cx, cy, cz, bl, bw, placed):
                    continue
                if any(check_overlap((cx, cy, cz), (bl, bw, bh),
                                     pb["pos"], pb["dim"])
                       for pb in placed):
                    continue
                score = cx + cy + cz + cz * box.weight_kg
                if score < best_score:
                    best_score = score;  best_pos = (cx, cy, cz);  best_ori = ori

        if best_pos:
            bx, by, bz = best_pos;  bl, bw, bh = best_ori
            placed.append({
                "id": box.id, "pos": best_pos, "dim": best_ori,
                "weight": box.weight_kg, "fragile": box.fragile,
                "original_box": box,
            })
            vol_packed += bl * bw * bh
            candidates.extend([(bx + bl, by, bz), (bx, by + bw, bz), (bx, by, bz + bh)])

    util_pct = (vol_packed / container.volume) * 100.0 if container.volume > 0 else 0.0
    return placed, util_pct


# ═══════════════════════════════════════════════════════════════════════════════
#  ALGORITHM 1  ─  GREEDY BEST-FIT DECREASING
# ═══════════════════════════════════════════════════════════════════════════════

def greedy_pack(
    boxes: List[Box],
    container: Container,
) -> Tuple[List[dict], float, float]:
    """
    Greedy Best-Fit Decreasing (BFD).

    Sort boxes by volume (largest first) then feed the sorted sequence into the
    core decoder.  Fast and deterministic; typically achieves 70-85% utilisation
    on balanced datasets.

    Returns
    -------
    placed      : placement list
    util_pct    : volume utilisation %
    elapsed_ms  : wall-clock time in milliseconds
    """
    t0 = time.time()
    sequence = sorted(boxes, key=lambda b: b.volume, reverse=True)
    placed, util = pack_sequence(sequence, container)
    return placed, util, (time.time() - t0) * 1_000


# ═══════════════════════════════════════════════════════════════════════════════
#  ALGORITHM 2  ─  GENETIC ALGORITHM
# ═══════════════════════════════════════════════════════════════════════════════

def genetic_algorithm(
    boxes: List[Box],
    container: Container,
    *,
    pop_size: int = 30,
    generations: int = 50,
    mutation_rate: float = 0.10,
    elite_frac: float = 0.25,
    progress_cb=None,
) -> Tuple[List[dict], float, float, List[float]]:
    """
    Genetic Algorithm for 3D Bin Packing.

    ┌─────────────────────────────────────────────────────────────┐
    │  Representation  :  permutation of boxes  (sequence)        │
    │  Decoder         :  pack_sequence()  (Best-Fit placement)   │
    │  Fitness         :  volume utilisation  %                   │
    │  Selection       :  elitism  (top elite_frac survive)       │
    │  Crossover       :  Order Crossover  (OX1)                  │
    │  Mutation        :  random swap  (probability mutation_rate) │
    │  Init. seed      :  greedy solution included in pop[0]      │
    └─────────────────────────────────────────────────────────────┘

    Parameters
    ----------
    boxes         : list of Box objects to pack
    container     : target Container
    pop_size      : number of individuals in the population
    generations   : number of evolutionary iterations
    mutation_rate : per-gene swap probability  (0 → 1)
    elite_frac    : fraction of top individuals carried over unchanged
    progress_cb   : optional callable(gen, total_gens, best_util)

    Returns
    -------
    placed          : best placement list found
    util_pct        : best volume utilisation %
    elapsed_ms      : wall-clock time in milliseconds
    fitness_history : best fitness per generation (for convergence plot)
    """
    t0 = time.time()
    n = len(boxes)
    elite_n = max(1, int(pop_size * elite_frac))

    # ── inner helpers ─────────────────────────────────────────────────────────

    def _fitness(individual: List[Box]) -> float:
        _, util = pack_sequence(individual, container)
        return util

    def _ox1(p1: List[Box], p2: List[Box]) -> List[Box]:
        """Order Crossover (OX1): preserves relative order from both parents."""
        a, b = sorted(random.sample(range(n), 2))
        child: List[Optional[Box]] = [None] * n
        child[a:b + 1] = p1[a:b + 1]
        seen = set(id(x) for x in child[a:b + 1])
        remaining = [x for x in p2 if id(x) not in seen]
        j = 0
        for i in range(n):
            if child[i] is None:
                child[i] = remaining[j];  j += 1
        return child  # type: ignore[return-value]

    def _mutate(individual: List[Box]) -> List[Box]:
        """Swap mutation: with probability mutation_rate swap each gene."""
        ind = individual[:]
        for i in range(n):
            if random.random() < mutation_rate:
                j = random.randint(0, n - 1)
                ind[i], ind[j] = ind[j], ind[i]
        return ind

    # ── population initialisation ─────────────────────────────────────────────
    population: List[List[Box]] = []
    # Seed with deterministic greedy solution for faster convergence
    greedy_seed = sorted(boxes, key=lambda b: b.volume, reverse=True)
    population.append(greedy_seed)
    while len(population) < pop_size:
        seq = boxes[:]
        random.shuffle(seq)
        population.append(seq)

    best_individual: List[Box] = greedy_seed[:]
    best_util = 0.0
    fitness_history: List[float] = []

    # ── evolutionary loop ─────────────────────────────────────────────────────
    for gen in range(generations):
        # Evaluate & sort
        scored = sorted(
            [(_fitness(ind), ind) for ind in population],
            key=lambda x: x[0],
            reverse=True,
        )
        gen_best = scored[0][0]
        fitness_history.append(gen_best)

        if gen_best > best_util:
            best_util = gen_best
            best_individual = scored[0][1][:]

        if progress_cb:
            progress_cb(gen, generations, best_util)

        # Elitism: carry top-k unchanged
        elites = [ind for _, ind in scored[:elite_n]]

        # Breed remainder via crossover + mutation
        new_pop = elites[:]
        while len(new_pop) < pop_size:
            p1, p2 = random.sample(elites, 2)
            child = _ox1(p1, p2)
            child = _mutate(child)
            new_pop.append(child)
        population = new_pop

    # Final decode with the best chromosome
    placed, util = pack_sequence(best_individual, container)
    return placed, util, (time.time() - t0) * 1_000, fitness_history


# ═══════════════════════════════════════════════════════════════════════════════
#  ALGORITHM 3  ─  SIMULATED ANNEALING
# ═══════════════════════════════════════════════════════════════════════════════

def simulated_annealing(
    boxes: List[Box],
    container: Container,
    *,
    initial_sequence: Optional[List[Box]] = None,
    T_start: float = 1_000.0,
    T_end: float = 0.1,
    cooling: float = 0.995,
    iters_per_step: int = 30,
    progress_cb=None,
) -> Tuple[List[dict], float, float]:
    """
    Simulated Annealing for 3D Bin Packing.

    ┌─────────────────────────────────────────────────────────────┐
    │  Representation  :  permutation of boxes  (sequence)        │
    │  Neighbour       :  random swap of two elements             │
    │  Acceptance      :  Metropolis criterion  exp(-Δ/T)         │
    │  Cooling         :  geometric schedule  T ← T × cooling     │
    │  Start           :  greedy solution (or provided sequence)  │
    └─────────────────────────────────────────────────────────────┘

    Parameters
    ----------
    boxes            : list of Box objects
    container        : target Container
    initial_sequence : warm-start sequence (defaults to greedy order)
    T_start          : initial temperature
    T_end            : termination temperature
    cooling          : multiplicative cooling factor  (< 1)
    iters_per_step   : neighbourhood evaluations per temperature step
    progress_cb      : optional callable(T_current, T_start, best_util)

    Returns
    -------
    placed      : best placement list found
    util_pct    : best volume utilisation %
    elapsed_ms  : wall-clock time in milliseconds
    """
    t0 = time.time()

    # Initialise from warm-start or greedy order
    current = (initial_sequence[:]
               if initial_sequence
               else sorted(boxes, key=lambda b: b.volume, reverse=True))

    cache: Dict[Tuple[int, ...], Tuple[List[dict], float]] = {}

    def _evaluate(seq: List[Box]) -> Tuple[List[dict], float]:
        key = tuple(box.id for box in seq)
        cached = cache.get(key)
        if cached is not None:
            return cached
        placed_eval, util_eval = pack_sequence(seq, container)
        cache[key] = (placed_eval, util_eval)
        return placed_eval, util_eval

    _, current_util = _evaluate(current)
    best_seq = current[:]
    best_placed, best_util = _evaluate(best_seq)

    T = T_start
    step = 0
    stale_steps = 0
    max_stale_steps = 6

    while T > T_end:
        improved_this_step = False
        for _ in range(iters_per_step):
            # Generate neighbour by swapping two random positions
            new_seq = current[:]
            i, j = random.sample(range(len(new_seq)), 2)
            new_seq[i], new_seq[j] = new_seq[j], new_seq[i]

            _, new_util = _evaluate(new_seq)
            delta = new_util - current_util

            # Metropolis acceptance
            if delta > 0 or random.random() < math.exp(delta / T):
                current = new_seq
                current_util = new_util

            if current_util > best_util:
                best_util = current_util
                best_seq = current[:]
                best_placed, best_util = _evaluate(best_seq)
                improved_this_step = True

        T *= cooling
        step += 1
        stale_steps = 0 if improved_this_step else stale_steps + 1

        if progress_cb and step % 5 == 0:
            progress_cb(T, T_start, best_util)

        # Stop early when SA is no longer improving the greedy baseline.
        if stale_steps >= max_stale_steps:
            break

    return best_placed, best_util, (time.time() - t0) * 1_000


# ═══════════════════════════════════════════════════════════════════════════════
#  3D VISUALISATION HELPER
# ═══════════════════════════════════════════════════════════════════════════════

def draw_box_3d(ax, pos, dim, color, alpha=0.55, highlight=False):
    """Draw a single 3D box as a Poly3DCollection on a matplotlib Axes3D."""
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    x, y, z = pos;  l, w, h = dim
    xx = [x, x+l, x+l, x, x, x+l, x+l, x]
    yy = [y, y,   y+w, y+w, y, y,   y+w, y+w]
    zz = [z, z,   z,   z,   z+h, z+h, z+h, z+h]
    faces = [[0,1,2,3],[4,5,6,7],[0,1,5,4],[2,3,7,6],[0,3,7,4],[1,2,6,5]]
    poly = Poly3DCollection(
        [[[xx[i], yy[i], zz[i]] for i in f] for f in faces],
        alpha=alpha,
        facecolor=color,
        edgecolor="#FFD700" if highlight else "#333333",
        linewidth=2.0 if highlight else 0.3,
    )
    ax.add_collection3d(poly)
